### ISSUE TITLE
Recommend using Taiwanese Mandarin instead of Traditional Chinese

### ISSUE THREAD

**Issue by siansiansu** [MiuLab/Taiwan-LLM#1]
Hello MiuLab,

Could you consider using **Taiwanese Mandarin** in place of **Traditional Chinese** for this project? I feel that this choice of language name aligns more closely with the project's essence. I'd love to hear your thoughts on this matter :)

Alex

**Comment by WangRongsheng** [comment]
good ideas!

**Comment by audreyt** [comment]
`cmn-Hant-TW` encodes the `Mandarin` language written in the `Han (Traditional variant)` script as used in `Taiwan`.

The suggested `Taiwanese Mandarin` means `cmn-TW` which implies `-Hant` without spelling it out.

Given that the model name `Taiwan-LLaMa` already encodes `-TW`, another possibility to consider is `Traditional Mandarin` which spells out the `cmn-Hant` part.

In either case — if MiuLab changes the description, I'm happy to sync my [downstream GGML repo](https://huggingface.co/audreyt/Taiwan-LLaMa-v1.0-GGML) to match.

**Comment by adamlin120** [comment]
Thanks for the thoughtful suggestions on renaming. The change to "Traditional Mandarin" aligns well with the essence of the project. The renaming has been implemented in the commit 93576b065f3780bed219d21234227e919c9c2014. Please feel free to review and share any further feedback or concerns.
