### ISSUE TITLE
pretrain model是否會開放?

### ISSUE THREAD

**Issue by cyc00518** [MiuLab/Taiwan-LLM#11]
謝謝開源模型,

想請問會開放pretrain model嗎?
因為想要基於你們模型基礎上再加上私有領域的知識,

謝謝您的耐心回答

**Comment by adamlin120** [comment]
目前不打算開放 pertained-only model。如果要加上特定領域知識，我推薦直接使用 prompt template 的格式下去訓練。

> A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: {user} ASSISTANT: {response} ... <Could be multi turn>

**Comment by cyc00518** [comment]
了解, 謝謝您
