### ISSUE TITLE
能否商用化？

### ISSUE THREAD

**Issue by thi23459112** [MiuLab/Taiwan-LLM#14]
你好
我有看到你們寫Apache-2.0 license，裡面包含可商用
但還是想跟你們確認一下

假設就直接拿你們的程式碼 原封不動商用以及demo在其他平台上 不知道是否ok?

**Comment by adamlin120** [comment]
v0.0 ~ v1.0模型經過了兩種資料的訓練 https://huggingface.co/datasets/yentinglin/zh_TW_c4 以及 [https://huggingface.co/datasets/yentinglin/traditional_mandarin_instructions](https://huggingface.co/datasets/yentinglin/traditional_mandarin_instructions%EF%BC%8C%E4%B9%9F%E5%8C%85%E5%90%AB%E4%BA%86) ，也包含了OpenAI 的資料 (https://openai.com/policies/terms-of-use) 。以上供您參考，最終判斷再麻煩您請教專業律師的意見。

**Comment by stphtan94117** [comment]
所以可以直接拿你們現有的東西商用囉？

**Comment by thi23459112** [comment]
意謂可以直接用你現在的專案模型商用？ 畢竟所有權是你們的

**Comment by adamlin120** [comment]
對於v0.0 ~ v1.0模型，如果您符合以上資料以及模型 (LLaMa License)的商用條件就可以。

**Comment by me-v2** [comment]
> v0.0 ~ v1.0模型經過了兩種資料的訓練 https://huggingface.co/datasets/yentinglin/zh_TW_c4 以及 [https://huggingface.co/datasets/yentinglin/traditional_mandarin_instructions](https://huggingface.co/datasets/yentinglin/traditional_mandarin_instructions%EF%BC%8C%E4%B9%9F%E5%8C%85%E5%90%AB%E4%BA%86) ，也包含了OpenAI 的資料 (https://openai.com/policies/terms-of-use) 。以上供您參考，最終判斷再麻煩您請教專業律師的意見。

link 404

**Comment by nicolaskodak** [comment]
@adamlin120 
感謝你們釋出模型讓大家使用🙏。

請問你提到「也包含了OpenAI 的資料 (https://openai.com/policies/terms-of-use) 」，是指使用 OpenAI API 的產出（ API response）作為部分的訓練資料嗎？

**Comment by nicolaskodak** [comment]
自問自答一下，我在 README.md 裡面找到了：

「The data included in this project were generated using OpenAI's models and are subject to OpenAI's Terms of Use. Please review [OpenAI's Terms of Use](https://openai.com/policies/terms-of-use) for details on usage and limitations.」

**Comment by adamlin120** [comment]
關於模型能不能商用，我建議您自行尋求法律意見。

模型作者 (Meta 與我) 都願意開放商用，但是 『"可以商用的模型” 訓練在 “有著作權法保護的資料上"，是否可以商用』需要您的判斷。

台灣沒有相關法案保護模型訓練在有著作權的資料上，但就我的理解，我們模型雖訓練在著作權資料上，但並沒有抄襲著作權人的意思表示，所以模型是可以商用的。

以上是我諮詢律師的結論，為求謹慎還請您尋求更專業的法律意見。
