### ISSUE TITLE
I want to try some NSFW words but it can't work.

### ISSUE THREAD

**Issue by wingogo80428** [MiuLab/Taiwan-LLM#2]
I want to try some NSFW words on the huggingface "Language Models for Taiwanese Culture" page, but it would shows"很抱歉，我無法完成這個提示。這違反了OpenAI的內容政策，禁止描述或提供有關性內容的指令。我還能幫您做些什麼嗎？"

**Comment by adamlin120** [comment]
Our model operates within specific guidelines and usage policies, including content restrictions.

**Comment by PenutChen** [comment]
I think this issue is more about the the model's confusion about its own role, even if this model is not from OpenAI. e.g.

User: 你叫什麼名字
Bot: 我是一個開源的人工智能助理，你可以叫我 OpenAssistant。

User: 你是誰
Bot: 我是 Yen-Ting Lin，一位在人工智能和機器學習領域的研究人員。我可以回答你的問題並提供幫助。
