### ISSUE TITLE
關於訓練相關資訊請教

### ISSUE THREAD

**Issue by ysf888app** [MiuLab/Taiwan-LLM#26]
感謝您無私分享！
想請教是否可分享本模型所使用Pretrain, Finetune訓練的腳本、步驟、環境、時間或注意事項等相關細節資訊。
謝謝！

**Comment by adamlin120** [comment]
推薦用 https://github.com/huggingface/trl/blob/main/examples/scripts/sft.py with Deepspeed stage 2

**Comment by ysf888app** [comment]
感謝:)
