### ISSUE TITLE
Data license

### ISSUE THREAD

**Issue by jhen0409** [MiuLab/Taiwan-LLM#3]
The data license badge of this repo is linked to stanford_alpaca (also for code license), just wanted to confirm if it's correct.

https://github.com/MiuLab/Taiwan-LLaMa/blob/93576b065f3780bed219d21234227e919c9c2014/README.md?plain=1#L13

**Comment by adamlin120** [comment]
Part of our instruction set is just a translation of Alpaca dataset, so it should follow the same license
