### ISSUE TITLE
config for  Taiwan-LLaMa-v1.0 demo on Hugging Face Spaces.

### ISSUE THREAD

**Issue by Syax19** [MiuLab/Taiwan-LLM#38]
您好，我正在使用您的Taiwan-LLaMa-v1.0模型執行去識別化任務，目前正在比較網頁app輸出的結果和fastchat API gen_model_answer對於同樣的prompt的output差異。

因為現在的Hugging face Spaces上的demo更新成Taiwan-LLM v2.0，之前沒有記錄到Max new tokens, Temperature, Top-p (nucleus sampling), Top-k的預設值，是否能請您提供這些資訊呢?

謝謝您

**Comment by PenutChen** [comment]
原本 Taiwan Llama 的 Demo Space 還在

https://huggingface.co/spaces/yentinglin/Taiwan-LLaMa2

可以透過 [Commit History](https://huggingface.co/spaces/yentinglin/Taiwan-LLaMa2/commits/main/app.py) 確認 Sample Parameters 的設定是什麼

**Comment by PenutChen** [comment]
Sample Parameters 在 9 天前有更動過

![image](https://github.com/MiuLab/Taiwan-LLaMa/assets/94501378/1b2df136-4051-473f-8558-ee3825ab77ba)

**Comment by Syax19** [comment]
找到了! 謝謝您的幫助!
