### ISSUE TITLE
關於https://chat.twllm.com 的程式構建

### ISSUE THREAD

**Issue by wrsnice** [MiuLab/Taiwan-LLM#39]
感謝您如何優秀的工作。

請問如何構建像https://chat.twllm.com/ 一樣的ChatUI？它是基於什麽程式碼編寫的？

**Comment by adamlin120** [comment]
It's a fork from https://github.com/huggingface/chat-ui

**Comment by wrsnice** [comment]
Thank you! Good jobs!
