### ISSUE TITLE
有關 Taiwan-LLM-7B-v2.1-chat 的 base model

### ISSUE THREAD

**Issue by larry0220** [MiuLab/Taiwan-LLM#45]
Hugging face 的 yentinglin/Taiwan-LLM-7B-v2.1-chat 寫著 Taiwan LLM based on Mistral-7B-v0.1
可是 config.json 卻顯示 
"architectures": [
   "LlamaForCausalLM"
 ]

**Comment by adamlin120** [comment]
原本是訓練一個 mistral 的模型，不過[當時用 FSDP 造成 loss 不穩定 ](https://github.com/huggingface/transformers/issues/26498#issuecomment-1741722014)，後來就改用 llama-2 了 :)

**Comment by DhruvaBansal00** [comment]
@adamlin120 did you train the llama-2 model using FSDP or Deepspeed?
