### ISSUE TITLE
Problem of quantisation

### ISSUE THREAD

**Issue by yihong1120** [MiuLab/Taiwan-LLM#47]
Hello all,
Shall you integrate Taiwan-LLM into [llama.cpp project](https://github.com/ggerganov/llama.cpp) and provide a much more effective lightweight model~

您好，
想詢問可否將Taiwan-LLM整合到[llama.cpp](https://github.com/ggerganov/llama.cpp)專案中，提供更有效的輕量級模型~

**Comment by adamlin120** [comment]
我不太熟悉 llama.cpp ，請問目前為何無法在 llama.cpp 直接用我們的模型呢？
