### ISSUE TITLE
是否會開源依此模型為基礎的Embedding model

### ISSUE THREAD

**Issue by D3annyC** [MiuLab/Taiwan-LLM#52]
如題，想問一下是否有規劃未來會開源以此模型為基礎的Embedding model呢？

**Comment by adamlin120** [comment]
你好， Embedding model 我們會持續更新在 [yentinglin/bert-base-zhtw](https://huggingface.co/yentinglin/bert-base-zhtw) 。

**Comment by D3annyC** [comment]
> 你好， Embedding model 我們會持續更新在 [yentinglin/bert-base-zhtw](https://huggingface.co/yentinglin/bert-base-zhtw) 。

感謝回覆 :)
