### ISSUE TITLE
Regarding using HuggingFaceEmbeddings and loading it onto the GPU 

### ISSUE THREAD

**Issue by WenTingTseng** [MiuLab/Taiwan-LLM#54]
Sorry, I'd like to ask. Why am I unable to use multi  CUDA GPU when using HuggingFaceEmbeddings? Even though I have already set it up.
 `model_kwargs={'device': 'cuda'}`
`encode_kwargs={"show_progress_bar": True,'device': device, 'batch_size': 1}`
`embeddings = HuggingFaceEmbeddings(model_name=model_name, model_kwargs=model_kwargs, encode_kwargs=encode_kwargs)`
 
Thanks a lot for your help !

**Comment by adamlin120** [comment]
Our model wont work as embedder
