### ISSUE TITLE
run script not work correct

### ISSUE THREAD

**Issue by MediconcenVictor** [MiuLab/Taiwan-LLM#6]
I already download Taiwan-LLaMa model
after I run `./run_text_generation_inference.sh yentinglin/Taiwan-LLaMa 8 ./Taiwan-LLaMa-v1.0 8080 2000 4000`
I got this error could you help me this , how do I resovle this problem 
![image](https://github.com/MiuLab/Taiwan-LLaMa/assets/99158541/de72a73e-e080-41a9-9dc3-61f5c276c45d)

not sure this api is exit or not , after I use this link seem this model api was not existed 
https://huggingface.co/api/models/yentinglin/Taiwan-LLaMa

**Comment by annahung31** [comment]
I guess you could try changing the link to
`https://huggingface.co/api/models/yentinglin/Taiwan-LLaMa-v0.0`
Or other model names listed in README:
[yentinglin/Taiwan-LLaMa-v0.0](https://huggingface.co/yentinglin/Taiwan-LLaMa-v0.0)
[yentinglin/Taiwan-LLaMa-v0.9](https://huggingface.co/yentinglin/Taiwan-LLaMa-v0.9)
[yentinglin/Taiwan-LLaMa-v1.0](https://huggingface.co/yentinglin/Taiwan-LLaMa-v1.0)

**Comment by Oliver0804** [comment]
@MediconcenVictor I ran into the same thing before. I tweaked the code a bit; you can check it out.

**Comment by adamlin120** [comment]
#9 updates the default model to v1.0

**Comment by geoxpert0001** [comment]
![image](https://github.com/MiuLab/Taiwan-LLaMa/assets/141697815/3d1211a5-96f2-43a1-9f77-b2638826c5ba)
出現此錯誤
