### ISSUE TITLE
Taiwan-LLaMa模型是否可商用？

### ISSUE THREAD

**Issue by frederickazion** [MiuLab/Taiwan-LLM#7]
你好，如題
原LLaMa2是可以商用模型，那經過台灣繁體中文資料微調訓練後，是否也是可商用模型呢？

**Comment by adamlin120** [comment]
v0.0 ~ v1.0模型經過了兩種資料的訓練 https://huggingface.co/datasets/yentinglin/zh_TW_c4 以及 https://huggingface.co/datasets/yentinglin/traditional_mandarin_instructions，也包含了 OpenAI 的資料 (https://openai.com/policies/terms-of-use) 。以上供您參考，最終判斷再麻煩您請教專業律師的意見。
